# HTML
# Archive your static HTML project and save it with the build record.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# trigger:
# - main

# pool:
#   vmImage: ubuntu-latest

# steps:
# - task: ArchiveFiles@2
#   inputs:
#     rootFolderOrFile: '$(build.sourcesDirectory)'
#     includeRootFolder: false
# - task: PublishBuildArtifacts@1

stages:
- stage: Build
  jobs:
  - job: BuildJob
    displayName: 'Build'
    steps:
    - task: CopyFiles@2
      inputs:
        Source: 'https://github.com/AliFarooq0172/DevOpsProj.git'
        Contents: 'project_files/**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)/project_files'
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
        includeRootFolder: true
    - task: PublishBuildArtifacts@1
      inputs:
        artifactName: 'html_artifact'
        publishLocation: 'pipeline'


