# HTML
# Archive your static HTML project and save it with the build record.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# trigger:
# - main

# pool:
#   vmImage: ubuntu-latest

# steps:
# - task: ArchiveFiles@2
#   inputs:
#     rootFolderOrFile: '$(build.sourcesDirectory)'
#     includeRootFolder: false
# - task: PublishBuildArtifacts@1

stages:
- stage: Build #BUILD STAGE
  jobs:
  - job: BuildJob
    displayName: 'Build'
    steps:
    - task: CopyFiles@2
      inputs:
        Source: 'https://github.com/AliFarooq0172/DevOpsProj.git'
        Contents: 'project_files/**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)/project_files'
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
        includeRootFolder: true
    - task: PublishBuildArtifacts@1
      inputs:
        artifactName: 'html_artifact'
        publishLocation: 'pipeline'

# - stage: Test  # SELENIUM TESTING STAGE
#   displayName: Test
#   jobs:
#   - job: RunSeleniumTests
#     displayName: Run Selenium Tests
#     pool:
#       vmImage: 'ubuntu-latest'
#     steps:
#     - task: SeleniumWebdriver@1
#       displayName: 'Run Selenium Tests'
#       inputs:
#         browser: 'chrome'
#         platform: 'Linux'
#         testFiles: '**/*.js'
#         options: '--headless'

- stage: Test # LambdaTest #SELENIUM TESTING STAGE
  displayName: 'Run Selenium Tests'
  jobs:
  - job: SeleniumTests
    displayName: 'Selenium Tests'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: LambdaTestTaskV1@1
      inputs:
        LambdaTestConfigFile: '<path-to-LT-config-file>'
        testFramework: 'selenium'
        seleniumBrowser: 'chrome'
        seleniumBrowserVersion: 'latest'
        seleniumPlatform: 'Windows 10'
        seleniumResolution: '1280x1024'
        seleniumTunnel: true
        SeleniumTestFiles: '**/*Tests.csproj'
        LambdaTestUsername: '$(LambdaTestUsername)'
        LambdaTestAccessKey: '$(LambdaTestAccessKey)'
