stages:
- stage: Build #BUILD STAGE
  jobs:
  - job: BuildJob
    displayName: 'Build'
    steps:
    - task: CopyFiles@2
      inputs:
        Source: 'https://github.com/AliFarooq0172/DevOpsProj.git'
        Contents: 'project_files/**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)/project_files'
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
        includeRootFolder: true
    - task: PublishBuildArtifacts@1
      inputs:
        artifactName: 'html_artifact'
        publishLocation: 'pipeline'

- stage: Test # SELENIUM TESTING STAGE
  jobs:
  - job: RunSeleniumTests
    displayName: 'Run Selenium Tests'
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: UseDotNet@2
      displayName: 'Install .NET Core SDK'
      inputs:
        packageType: 'sdk'
        version: '3.x'
    - task: NuGetToolInstaller@1
      displayName: 'Install NuGet'
      inputs:
        versionSpec: '>= 5.0.0'
        checkLatest: true
      env:
        nugetConfigPath: '$(Build.SourcesDirectory)/NuGet.config'
    - task: NuGetCommand@2
      displayName: 'Restore packages'
      inputs:
        command: 'restore'
        restoreSolution: '**/*.sln'
        feedsToUse: 'config'
        nugetConfigPath: '$(Build.SourcesDirectory)/NuGet.config'
    - task: VSTest@2
      displayName: 'Run Selenium Unit Tests'
      inputs:
        testSelector: 'testAssemblies'
        testAssemblyVer2: |
          **/*UnitTests.dll
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'
        runInParallel: true
        codeCoverageEnabled: true