stages:
- stage: Build #BUILD STAGE
  jobs:
  - job: BuildJob
    displayName: 'Build'
    steps:
    - task: CopyFiles@2
      inputs:
        Source: 'https://github.com/AliFarooq0172/DevOpsProj.git'
        Contents: 'project_files/**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)/project_files'
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
        includeRootFolder: true
    - task: PublishBuildArtifacts@1
      inputs:
        artifactName: 'html_artifact'
        publishLocation: 'pipeline'

- stage: Test # SELENIUM TESTING STAGE
  jobs:
  - job: RunSeleniumTests
    displayName: 'Run Selenium Tests'
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: UseDotNet@2
      displayName: 'Install .NET Core SDK'
      inputs:
        packageType: 'sdk'
        version: '3.x'
    - task: VSTest@2
      displayName: 'Run Selenium Unit Tests'
      inputs:
        testSelector: 'testAssemblies'
        testAssemblyVer2: |
          **/*UnitTests.dll
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'
        runInParallel: true
        codeCoverageEnabled: true
  - deployment: DeployToStaging
    displayName: 'Deploy to Staging Environment'
    environment: 'Staging'
    dependsOn: RunSeleniumTests
    pool:
      vmImage: 'windows-latest'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'html_artifact'
              downloadPath: '$(System.ArtifactsDirectory)'
          - task: PowerShell@2
            displayName: 'Deploy to Staging Environment'
            inputs:
              targetType: 'inline'
              script: |
                Write-Host 'Deploying to Staging environment...'

                # Copy the HTML and CSS files to the web server's document root
                Copy-Item -Path $(System.ArtifactsDirectory)/html_artifact/project_files -Destination C:\inetpub\wwwroot -Recurse

                # Configure the web server to serve the HTML and CSS files
                Add-Content -Path C:\inetpub\wwwroot\web.config -Value '<system.webServer><staticContent><mimeMap fileExtension=".html" mimeType="text/html" /><mimeMap fileExtension=".css" mimeType="text/css" /></staticContent></system.webServer>'

                # Restart the web server to apply the configuration changes
                Restart-Service -Name W3SVC

                # Test the deployment by accessing the website using a web browser
                $ie = New-Object -ComObject InternetExplorer.Application
                $ie.Visible = $true
                $ie.Navigate2('http://localhost')

- stage: Release
  dependsOn: Test
  jobs:
  - deployment: DeployToDev
    displayName: 'Deploy to Dev Environment'
    environment: 'Dev'
    pool:
      vmImage: 'windows-latest'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'html_artifact'
              downloadPath: '$(System.ArtifactsDirectory)'
          - task: PowerShell@2
            displayName: 'Deploy to Dev Environment'
            inputs:
              targetType: 'inline'
              script: |
                Write-Host 'Deploying to Dev environment...'
                # Run deployment scripts or commands here
  - deployment: ApprovalGate
    displayName: 'Pre-Deployment Approval'
    dependsOn: DeployToDev
    environment: 'Dev'
    pool:
      vmImage: 'windows-latest'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: ManualIntervention@8
            displayName: 'Request Approval'
            inputs:
              instructions: 'Please approve this deployment.'
              timeoutInMinutes: 60
              onTimeout: reject
              emailRecipients: |
                k190172@nu.edu.pk
                k190145@nu.edu.pk
