# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
  - repository: DevOpsProj
    type: github
    endpoint: MyGitHubServiceConnection
    name: AliFarooq0172/DevOpsProj

stages:
- stage: Build # BUILD STAGE
  jobs:
  - job: Build
    displayName: 'Build'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        echo Building code...
    # Add more steps to build your code

- stage: Release # RELEASE STAGE
  # dependsOn: Test
  jobs:
  - deployment: DeployToDev
    displayName: 'Deploy to Dev Environment'
    environment: 'Dev'
    pool:
      vmImage: 'windows-latest'
    strategy:
      runOnce:
        deploy:
          steps:
          # - task: DownloadBuildArtifacts@0
          #   inputs:
          #     buildType: 'current'
          #     downloadType: 'single'
          #     artifactName: 'html_artifact'
          #     downloadPath: '$(System.ArtifactsDirectory)'
          - task: PowerShell@2
            displayName: 'Deploy to Dev Environment'
            inputs:
              targetType: 'inline'
              script: |
                Write-Host 'Deploying to Dev environment...'
                # Run deployment scripts or commands here
    # Add a pre-deployment approval gate
  - deployment: ApprovalGate
    displayName: 'Pre-Deployment Approval'
    dependsOn: DeployToDev
    environment: 'Dev'
    pool:
      vmImage: 'windows-latest'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: PowerShell@2
            displayName: 'Request Approval'
            inputs:
              targetType: 'inline'
              script: |
                Write-Host 'Waiting for approval...'
                # Run commands to request approval
